//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HearingSolutionWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kiosk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kiosk()
        {
            this.KioskHeartbeats = new HashSet<KioskHeartbeat>();
            this.KioskLocations = new HashSet<KioskLocation>();
            this.KioskOwnerships = new HashSet<KioskOwnership>();
        }
    
        public System.Guid Id { get; set; }
        public string KioskID { get; set; }
        public string StoreContact { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public string KioskType { get; set; }
        public string KioskDisplayName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KioskHeartbeat> KioskHeartbeats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KioskLocation> KioskLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KioskOwnership> KioskOwnerships { get; set; }
    }
}
