//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HearingSolutionWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KioskHeartbeat
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> HeartbeatTime { get; set; }
        public string PaperStatus { get; set; }
        public System.Guid Kiosk_Id { get; set; }
    
        public virtual Kiosk Kiosk { get; set; }
    }
}
