//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HearingSolutionWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KioskOwnership
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KioskOwnership()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> OwnershipStart { get; set; }
        public Nullable<System.DateTime> OwnershipEnd { get; set; }
        public string AspNetUsers_Id { get; set; }
        public System.Guid Kiosk_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Kiosk Kiosk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
