//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HearingSolutionWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string AdressLine1 { get; set; }
        public string AdressLine2 { get; set; }
        public string AdressLine3 { get; set; }
        public string Postcode { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string Age { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<System.DateTime> DateTaken { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public Nullable<System.DateTime> DateUploaded { get; set; }
        public Nullable<int> SectionOneScore { get; set; }
        public Nullable<int> SectionTwoScore { get; set; }
        public Nullable<int> SectionThreeScore { get; set; }
        public Nullable<int> TotalScore { get; set; }
        public string TestOneQ1 { get; set; }
        public string TestOneQ2 { get; set; }
        public string TestOneQ3 { get; set; }
        public string TestOneQ4 { get; set; }
        public string TestOneQ5 { get; set; }
        public string TestTwoQ1 { get; set; }
        public string TestTwoQ2 { get; set; }
        public string TestTwoQ3 { get; set; }
        public string TestTwoQ4 { get; set; }
        public string TestTwoQ5 { get; set; }
        public string TestTwoQ6 { get; set; }
        public string TestTwoQ7 { get; set; }
        public string TestTwoQ8 { get; set; }
        public string TestThreeQ1 { get; set; }
        public string TestThreeQ2 { get; set; }
        public string TestThreeQ3 { get; set; }
        public string TestThreeQ4 { get; set; }
        public string TestThreeQ5 { get; set; }
        public Nullable<decimal> TimeTaken { get; set; }
        public Nullable<System.Guid> TransactionFolders_Id { get; set; }
        public System.Guid KioskOwnership_Id { get; set; }
        public Nullable<bool> IsSuccessful { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual KioskOwnership KioskOwnership { get; set; }
        public virtual TransactionFolder TransactionFolder { get; set; }
    }
}
